### ISSUE TITLE
D3 transform console errors

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#16]
an example from the console...

Error: Invalid value for <g> attribute transform="translate(-432.2114843779007,--98.58720074961448)scale(3)"

Seeing quite a few of these as I navigate around, what is the root cause.

**Comment by benlogan** [comment]
@satyashani was this fixed, what was the problem?

**Comment by satyashani** [comment]
A minor typo in an svg element attribute.

**Comment by benlogan** [comment]
I'm still seeing these errors, e.g.
Error: Invalid value for <g> attribute transform="translate(-1728.9442363222095,-1072.0190620728176scale(3)"
