### ISSUE TITLE
jquery.qtip.min.js.map is missing - console errors

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#17]
GET http://127.0.0.1:56025/contents/js/jquery.qtip.min.js.map 404 (Not Found)

Also, what is this used for?

**Comment by satyashani** [comment]
Need not worry about it -
http://stackoverflow.com/questions/23570843/qtip2-loads-a-jquery-qtip-min-map-from-internet-and-slows-down-site

**Comment by benlogan** [comment]
Thanks, got it!
