### ISSUE TITLE
403's on loading of movie images

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#18]
e.g. GET http://ia.media-imdb.com/images/M/MV5BMTYxMTEzNTgzM15BMl5BanBnXkFtZTcwMjg1MzAwMQ@@._V1_SX300.jpg 403 (Forbidden)

I did see this working once or twice, so might be an intermittent bug...

**Comment by satyashani** [comment]
I think imdb api doesn't allow images to be loaded directly from other domains due to cross domain request restrictions, when running from localhost images always load.

**Comment by satyashani** [comment]
We might have to make the imdb api call on server side using some scripting languages and then supply image under out own domain.

**Comment by benlogan** [comment]
OK. For now, given the number of movies, you may as well just download them and store them in our project? We don’t really have an app server and I don’t want to build a complex middle-tier for this project. Can you just grab them manually please?
