### ISSUE TITLE
Movie Data - cleanup

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#23]
movielist.json - remove movie date/year from the name field, it already exists as a separate property -  'year'. 

in the search box - don't add the year, just autocomplete on title.

in the movie summary - continue to add the year, but do it by properly joining the two fields (name and year) and make sure there is a space inbetween the two.

**Comment by satyashani** [comment]
Removing year from search box requires big change. Search box is simple input box, so we need the name in it to be unique to identify which movie is selected for larger view. There are sometimes two movies of same name created in different years.

**Comment by benlogan** [comment]
Year in the search field is fine - the main thing was that the json was cleaned up. I will close this now.
