### ISSUE TITLE
Small toolbox for any options - e.g labels checkbox

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#5]
The labels checkbox will be off my default, but selecting it will show a truncated label for the main field relating to that node, e.g. movie title.

**Comment by satyashani** [comment]
This label has to be displayed on the node on graph right?

**Comment by benlogan** [comment]
Looks ok, but a few improvements needed. Let's truncate it with a "..." if the label is longer than 10 characters. Let's also make sure the text label is in front of the node, at the moment it is behind and partially hidden. The biggest improvement would be if we could lengthen the arc between nodes when labels are shown, to give them more space and make them more readable - in other words spread out the nodes and use more of the screen.
![screen shot 2015-04-09 at 13 45 58](https://cloud.githubusercontent.com/assets/1737958/7066898/cd0c3478-debe-11e4-8e3c-a9503f02fdf4.png)
